runtime: python
env: flex
runtime_config:
        python_version: 3
entrypoint: gunicorn -b :$PORT main:app
env_variables:
        mysql+pymysql://USER:PASSWORD@/DATABASE?unix_socket=/cloudsql/INSTANCE_CONNECTION_NAME
beta_settings:
        cloud_sql_instances: INSTANCE_CONNECTION_NAME
